# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 14:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actuacio',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'actuacio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActualitzacioDades08072015',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codi_aca', models.CharField(blank=True, max_length=200, null=True)),
                ('utmx_etrs89', models.CharField(blank=True, max_length=200, null=True)),
                ('utmy_etrs89', models.CharField(blank=True, max_length=200, null=True)),
                ('localitzacio', models.CharField(blank=True, max_length=200, null=True)),
                ('codi_sp', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cita', models.CharField(blank=True, max_length=200, null=True)),
                ('autor_cita', models.CharField(blank=True, max_length=200, null=True)),
                ('font_cita', models.CharField(blank=True, max_length=200, null=True)),
                ('observacions', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'actualitzacio_dades_08_07_2015',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Citacions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
                ('idspinvasora', models.CharField(blank=True, max_length=100, null=True)),
                ('grup', models.CharField(blank=True, max_length=255, null=True)),
                ('utmx', models.FloatField(blank=True, null=True)),
                ('utmy', models.FloatField(blank=True, null=True)),
                ('localitat', models.CharField(blank=True, max_length=255, null=True)),
                ('municipi', models.CharField(blank=True, max_length=255, null=True)),
                ('comarca', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('autor_s', models.CharField(blank=True, max_length=255, null=True)),
                ('citacio', models.CharField(blank=True, max_length=255, null=True)),
                ('font', models.CharField(blank=True, max_length=255, null=True)),
                ('referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('observacions', models.CharField(blank=True, max_length=4000, null=True)),
                ('tipus_cita', models.CharField(blank=True, max_length=100, null=True)),
                ('habitat', models.CharField(blank=True, max_length=100, null=True)),
                ('tipus_mort', models.CharField(blank=True, max_length=100, null=True)),
                ('abundancia', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_aca', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_estacio', models.CharField(blank=True, max_length=100, null=True)),
                ('ind_ha', models.FloatField(blank=True, null=True)),
                ('ind_capt', models.IntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'citacions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comarques',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('codicomar', models.CharField(blank=True, max_length=254, null=True)),
                ('nomcomar', models.CharField(blank=True, max_length=254, null=True)),
                ('areacomar', models.FloatField(blank=True, null=True)),
                ('dataalta', models.CharField(blank=True, max_length=200, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comarques_4326',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConquesPrincipals',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_aca', models.CharField(blank=True, max_length=254, null=True)),
                ('nom_conca', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'conques_principals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'document',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('iddocument', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titol', models.CharField(blank=True, max_length=500, null=True)),
                ('observacions', models.CharField(blank=True, max_length=500, null=True)),
                ('nomoriginal', models.CharField(blank=True, max_length=255, null=True)),
                ('fitxer', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especieinvasora',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('observacions', models.CharField(blank=True, max_length=4000, null=True)),
                ('present_catalogo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'especieinvasora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExoaquaToExocat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_exoaqua', models.CharField(blank=True, max_length=100, null=True)),
                ('id_exocat', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'exoaqua_to_exocat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Extensions',
            fields=[
                ('idextensio', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('extensio', models.CharField(blank=True, max_length=25, null=True)),
                ('descripcio', models.CharField(blank=True, max_length=500, null=True)),
                ('fitxericona', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'extensions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'grup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Grupespecie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'grupespecie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('habitat', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'habitat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitatespecie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'habitatespecie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imatge',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imatge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imatges',
            fields=[
                ('idimatge', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('titol', models.CharField(blank=True, max_length=4000, null=True)),
                ('observacions', models.CharField(blank=True, max_length=500, null=True)),
                ('nomoriginal', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.BinaryField(blank=True, null=True)),
                ('fitxer', models.BinaryField(blank=True, null=True)),
                ('visualitzable', models.CharField(blank=True, max_length=1, null=True)),
                ('tag', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'imatges',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MassaAiguaTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_taxon_exoaqua', models.CharField(blank=True, max_length=100, null=True)),
                ('id_localitzacio', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'massa_aigua_taxon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MassesAigua',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(blank=True, max_length=100, null=True)),
                ('codi_aca', models.CharField(blank=True, max_length=100, null=True)),
                ('tipus_geom', models.CharField(blank=True, max_length=1, null=True)),
                ('nom', models.CharField(blank=True, max_length=254, null=True)),
                ('idconca', models.CharField(blank=True, max_length=100, null=True)),
                ('idcategor', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'masses_aigua',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomvulgar',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomvulgar', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'nomvulgar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nomvulgartaxon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'nomvulgartaxon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PresenciaSp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'presencia_sp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quadricula',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('precision_m', models.FloatField(blank=True, null=True)),
                ('resolution', models.FloatField(blank=True, null=True)),
                ('code_utm_10', models.CharField(blank=True, max_length=4, null=True)),
                ('field_xmin', models.FloatField(blank=True, db_column='_xmin', null=True)),
                ('field_xmax', models.FloatField(blank=True, db_column='_xmax', null=True)),
                ('field_ymin', models.FloatField(blank=True, db_column='_ymin', null=True)),
                ('field_ymax', models.FloatField(blank=True, db_column='_ymax', null=True)),
                ('quadre', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('geom_4326', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'quadricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuadTemp',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('precision_field', models.DecimalField(blank=True, db_column='precision_', decimal_places=65535, max_digits=65535, null=True)),
                ('resolution', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('code_utm_1', models.CharField(blank=True, max_length=254, null=True)),
                ('field_xmin', models.DecimalField(blank=True, db_column='__xmin', decimal_places=65535, max_digits=65535, null=True)),
                ('field_xmax', models.DecimalField(blank=True, db_column='__xmax', decimal_places=65535, max_digits=65535, null=True)),
                ('ymin', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ymax', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('id_show', models.CharField(blank=True, max_length=254, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'quad_temp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regionativa',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'regionativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nomsp', models.CharField(blank=True, max_length=100, null=True)),
                ('tesaurebiocat', models.CharField(blank=True, max_length=100, null=True)),
                ('codibiocat', models.CharField(blank=True, max_length=100, null=True)),
                ('genere', models.CharField(blank=True, max_length=100, null=True)),
                ('especie', models.CharField(blank=True, max_length=100, null=True)),
                ('autorespecie', models.CharField(blank=True, max_length=100, null=True)),
                ('subespecie', models.CharField(blank=True, max_length=100, null=True)),
                ('autorsubespecie', models.CharField(blank=True, max_length=100, null=True)),
                ('varietat', models.CharField(blank=True, max_length=100, null=True)),
                ('autorvarietat', models.CharField(blank=True, max_length=100, null=True)),
                ('subvarietat', models.CharField(blank=True, max_length=100, null=True)),
                ('autorsubvarietat', models.CharField(blank=True, max_length=100, null=True)),
                ('forma', models.CharField(blank=True, max_length=100, null=True)),
                ('autorforma', models.CharField(blank=True, max_length=100, null=True)),
                ('codieorca', models.CharField(blank=True, max_length=100, null=True)),
                ('familia', models.CharField(blank=True, max_length=100, null=True)),
                ('taxonomicelements_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scientificname', models.CharField(blank=True, max_length=100, null=True)),
                ('highertaxon', models.CharField(blank=True, max_length=100, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=100, null=True)),
                ('phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('taxonomicelement_class', models.CharField(blank=True, max_length=100, null=True)),
                ('taxonomicelement_order', models.CharField(blank=True, max_length=100, null=True)),
                ('family', models.CharField(blank=True, max_length=100, null=True)),
                ('genus', models.CharField(blank=True, max_length=100, null=True)),
                ('specificepithet', models.CharField(blank=True, max_length=100, null=True)),
                ('infraspecificrank', models.CharField(blank=True, max_length=100, null=True)),
                ('infraspecificepithet', models.CharField(blank=True, max_length=100, null=True)),
                ('authoryearofscientificname', models.CharField(blank=True, max_length=100, null=True)),
                ('nomenclaturalcode', models.CharField(blank=True, max_length=100, null=True)),
                ('c_esp', models.CharField(blank=True, max_length=100, null=True)),
                ('c_e_o', models.CharField(blank=True, max_length=100, null=True)),
                ('c_pcsb', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'taxon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaentrada',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('viaentrada', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'viaentrada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viaentradaespecie',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'viaentradaespecie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zonageografica',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'zonageografica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CitacionsEspecie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(blank=True, max_length=255, null=True)),
                ('idspinvasora', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
                ('comarca', models.CharField(blank=True, max_length=100, null=True)),
                ('municipi', models.CharField(blank=True, max_length=255, null=True)),
                ('localitat', models.CharField(blank=True, max_length=255, null=True)),
                ('finca', models.CharField(blank=True, max_length=255, null=True)),
                ('paratge', models.CharField(blank=True, max_length=255, null=True)),
                ('utmx', models.FloatField(blank=True, null=True)),
                ('utmy', models.FloatField(blank=True, null=True)),
                ('utmz', models.FloatField(blank=True, null=True)),
                ('utm_10', models.CharField(blank=True, max_length=4, null=True)),
                ('utm_1', models.CharField(blank=True, max_length=6, null=True)),
                ('propietari_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('adreca', models.CharField(blank=True, max_length=255, null=True)),
                ('poblacio', models.CharField(blank=True, max_length=255, null=True)),
                ('telefon', models.CharField(blank=True, max_length=255, null=True)),
                ('qual_terreny', models.CharField(blank=True, max_length=255, null=True)),
                ('espai_natural_protegit', models.CharField(blank=True, max_length=255, null=True)),
                ('espai_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('superficie_ocupada', models.CharField(blank=True, max_length=100, null=True)),
                ('presencia', models.CharField(blank=True, max_length=255, null=True)),
                ('estat_invasio', models.CharField(blank=True, max_length=255, null=True)),
                ('observacions', models.CharField(blank=True, max_length=4000, null=True)),
                ('grup', models.CharField(blank=True, max_length=255, null=True)),
                ('imatge_detall_espcie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citacio_imatge_detall_especie', to='exocatsite.Imatges')),
                ('imatge_detall_localitat_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citacio_imatge_detall_localitat_1', to='exocatsite.Imatges')),
                ('imatge_detall_localitat_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citacio_imatge_detall_localitat_2', to='exocatsite.Imatges')),
                ('imatge_panoramica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='citacio_imatge_panoramica', to='exocatsite.Imatges')),
            ],
            options={
                'db_table': 'citacions_especie',
                'managed': True,
            },
        ),
    ]
