# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacionsespecie',
            name='NIP',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citacionsespecie',
            name='contacte',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
