# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0002_auto_20180322_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citacionsespecie',
            name='imatge_detall_espcie',
        ),
        migrations.RemoveField(
            model_name='citacionsespecie',
            name='imatge_detall_localitat_1',
        ),
        migrations.RemoveField(
            model_name='citacionsespecie',
            name='imatge_detall_localitat_2',
        ),
        migrations.RemoveField(
            model_name='citacionsespecie',
            name='imatge_panoramica',
        ),
        migrations.AddField(
            model_name='citacionsespecie',
            name='imatges',
            field=models.FileField(blank=True, null=True, upload_to='imatges'),
        ),
        migrations.AlterField(
            model_name='citacionsespecie',
            name='idspinvasora',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exocatsite.Especieinvasora'),
        ),
    ]
