# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-05 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0004_auto_20180404_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imatgescitacions',
            old_name='url',
            new_name='fitxer',
        ),
        migrations.AddField(
            model_name='imatgescitacions',
            name='data_pujada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imatgescitacions',
            name='tipus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
