# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-08 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0007_auto_20180426_1632'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imatge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='imatges',
            options={'managed': False},
        ),
        migrations.AddField(
            model_name='citacionsespecie',
            name='usuari',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
