# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0008_auto_20180508_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='citacionsespecie',
            name='data_creacio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citacionsespecie',
            name='data_modificacio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
