# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-02 10:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import exocatsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('exocatsite', '0009_auto_20180515_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitacionsACA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_especie', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_ma', models.CharField(blank=True, max_length=255, null=True)),
                ('codi_especie', models.CharField(blank=True, max_length=255, null=True)),
                ('data_cita', models.CharField(blank=True, max_length=255, null=True)),
                ('nom_ma', models.CharField(blank=True, max_length=255, null=True)),
                ('grup', models.CharField(blank=True, max_length=255, null=True)),
                ('categoria_aca', models.CharField(blank=True, max_length=255, null=True)),
                ('utm_x', models.FloatField(blank=True, null=True)),
                ('utm_y', models.FloatField(blank=True, null=True)),
                ('localitzacio', models.CharField(blank=True, max_length=500, null=True)),
                ('autor_cita', models.CharField(blank=True, max_length=255, null=True)),
                ('font_cita', models.CharField(blank=True, max_length=255, null=True)),
                ('observacions', models.CharField(blank=True, max_length=500, null=True)),
                ('data', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'citacions_ACA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='citacionsespecie',
            name='geom_4326',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='imatgescitacions',
            name='temporal',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imatgescitacions',
            name='fitxer',
            field=models.FileField(blank=True, null=True, upload_to=exocatsite.models.upload_path_handler),
        ),
    ]
